[[constraint]]
  # v1.0.5
  name = "github.com/hyperledger/fabric"
  version = "1.0.5"

[[constraint]]
  name = "github.com/hyperledger/fabric-sdk-go"
  revision = "614551a752802488988921a730b172dada7def1d"